### ISSUE TITLE
Screen resize feature issue

### ISSUE THREAD

**Issue by bbsskk** [slashmax/AAMirror#10]
I tested a new version on my rooted phone
It showed the full AA screen . Good job
But after I disconnected my phone, the phone screen was still fitted to AA screen size.
and a home key and a back key of the phone were not working
I can't get it back

**Comment by VantageT** [comment]
I think he fixed that now. The only thing for me is that the screen resize happens everytime we switch to the OEM tab from another AA tab or from another source such as SiriusXM. Because of this one of my custom apps keeps restarting due to a resolution change. I was wondering if this could be fixed by changing the screen resolution back to the original either when the AA stream has stopped or the usb cable has been unplugged.

**Comment by slashmax** [comment]
added options to control screen rotation and size reset on focus lost (switch app/screen off)
